Repository geneweb/geneweb, pull requests merged in 2018-10, with the labels that each got.

#690 Adding Corsican translation to GeneWeb
  hd/etc/copyr.txt
  hd/etc/index.txt
  hd/images/flags/l-co.jpg
  hd/images/flags/t-co.png
  hd/lang/lex_utf8.txt
  hd/lang/start_utf8.txt
  hd/lang/version.txt
  setup/lang/welcome.htm
Labels: lexicon

#683 Better CSS when changing children names, focus on parent after changes
  hd/etc/js.txt
  lib/changeChildren.ml
Labels: enhancement, template

#686 Small improvements to gui
  gui/gui.ml
  gui/gw/gui_lex.txt
Labels: enhancement
