Repository geneweb/geneweb, pull requests merged in 2023-06, with the labels that each got.

#1478 Update lexicon.txt to cause proper dates in Russian
  hd/lang/lexicon.txt
Labels: traduction

#1358 Clarify on %s's side message for cousinsDisplay
  hd/lang/lexicon.txt
  lib/cousinsDisplay.ml
Labels: Template

#1483 Fix marriage list in statistics.
  lib/birthDeathDisplay.ml
Labels: Bug, Template
