Repository geneweb/geneweb, pull requests merged in 2024-12, with the labels that each got.

#1956 Do not expand Makefile variables in double-quoted shell strings
  Makefile
Labels: build

#1993 GitHub Actions workflow optimization and improvements
  .github/workflows/ci.yml
  Makefile
  dune-project
  geneweb.opam
Labels: build

#1976 notesDisplay: Modernize directory listings with tree view structure
  hd/etc/accent.txt
  hd/etc/characters.txt
  hd/etc/css/css.css
  hd/etc/js.txt
  hd/etc/summary.txt
  hd/etc/toolbar.txt
  hd/etc/updfam.txt
  hd/etc/updind.txt
  hd/lang/lexicon.txt
  lib/hutil.ml
  lib/hutil.mli
  lib/notesDisplay.ml
  lib/wiki.ml
  lib/wiki.mli
  lib/wiznotesDisplay.ml
Labels: Template

#2011 Optimize Docker CI Workflow and Build Process
  .github/workflows/docker.yml
  docker/Dockerfile
  docker/geneweb-launch.sh
Labels: docker, build/CI
